### ISSUE TITLE
cause of the SQL crash

### ISSUE THREAD

**Issue by NjbBzz** [pipiche38/domoticz-sqlite3-issue#1]
Hi 
The cause of the crash is coming from the use of "detect_types=sqlite3.PARSE_DECLTYPES" in the sqlite3.connect command.
I tested with removing it and there is no more crash.
Yet, I assume that it's needed as you're using custom types ; I think you should have a look at the use of sqlite3.PARSE_COLNAMES istead for "detect_types" ; another way is to study the use of type converters to convert Python types to SQL and vice-versa : see this page :  https://docs.python.org/3/library/sqlite3.html#sqlite3-types (search for chapter : Converting SQLite values to custom Python types)

**Comment by Hedda** [comment]
@NjbBzz & @pipiche38 Submitted issue to upstream zigpy for their attention. Please also provide feedback in -> https://github.com/zigpy/zigpy/issues/702

**Comment by puddly** [comment]
This plugin crashes the official Docker image for me about 90% of the time. Restarting it causes the container to crash on startup within 10 seconds.

```Python
"""
<plugin key="PythonSQLiteTest" name="Python SQLite Test" author="puddly" version="0.0.1" wikilink="https://github.com/zigpy/zigpy/issues/702" externallink="https://example.org/">
    <description>Python SQLite test</description>
    <params></params>
</plugin>
"""

import sqlite3
import Domoticz


def onStart():
    con = sqlite3.connect(":memory:", detect_types=sqlite3.PARSE_DECLTYPES)

    cur = con.cursor()

    cur.execute("CREATE TABLE test (custom custom, number);")
    cur.execute("INSERT INTO test VALUES('value1', 1);")
    cur.execute("INSERT INTO test VALUES('value2', 2);")

    cur.execute('SELECT * FROM test')
    cur.fetchall()

    con.close()
```

The Python environment within the Docker image doesn't include unit tests but if you run any of the official CPython ones in a plugin, they will also sometimes segfault: https://github.com/python/cpython/search?q=PARSE_DECLTYPES+unittest

Hopefully this minimal example is enough for @gizmocuz to take a look at the problem again. `sqlite3` is a part of the standard library so it has to work.

**Comment by Hedda** [comment]
@NjbBzz or @pipiche38 Could you try submitting puddly's plugin as a new issue to https://github.com/domoticz/domoticz/issues/ ?

**Comment by pipiche38** [comment]
Maybe I missed something but I do not understand why you want to report it to domoticz, while the issue seems to be pointed to the use of detect_types=sqlite3.PARSE_DECLTYPES which is done by zigpy.

**Comment by Hedda** [comment]
Think puddly means that his "Python SQLite Test" plugin above contain valid custom use in detect_types=sqlite3.PARSE_DECLTYPES that segfaults Domoticz's Docker even though it should not crash thus pointing to there still being a problem with Domoticz.

> "sqlite3 is a part of the Python standard library so it has to work."

So even if zigpy could perhaps be refactored not to use custom detect_types=sqlite3.PARSE_DECLTYPES maybe it does not have to if its use is valid, and valid use of custom like in puddly's "Python SQLite Test" plugin above should really not crash Domoticz.

Why does puddly's "Python SQLite Test" plugin crash Domoticz 90% of the when that should be a valid use?

Maybe just as important, why does even [the official CPython unittest](https://github.com/python/cpython/search?q=PARSE_DECLTYPES+unittest) sometimes segfault Domoticz if they are used in a plugin? 

https://github.com/python/cpython/search?q=PARSE_DECLTYPES+unittest

https://github.com/python/cpython/blob/e161ec5dd7ba9355eb06757b9304019ac53cdf69/Lib/sqlite3/test/types.py

https://github.com/python/cpython/blob/3b4b2cf418707c79f96689e401e3c703c0fdd4d2/Lib/sqlite3/test/regression.py

If even unittest with sqlite3 crash Domoticz probably have deeper issues with sqlite3 in plugins then the issues we see here?

**Comment by NjbBzz** [comment]
Hi
I've tested both options PARSE_DECLTYPES and PARSE_COLNAMES with registration of adapter and converter.
The 1st option still crashes while the second doesn't : it seems only the PARSE_COLNAMES is supported by Domoticz plugin.
I saw that @puddly tested it also but unfortunately it failed : I don't know why.

**Comment by Hedda** [comment]
See https://github.com/zigpy/zigpy/issues/702 for a short answer from developers regarding the question of refactoring zigpy. Summary of the answer is this:
 
The right place to fix this issue is in Domoticz, (not in zigpy), as being built-in, the sqlite3 module should not segfault Domoticz.

If it is needed for a Domoticz plugin then I custom fork of zigpy could be a solution as no plans to refactor this in upstream.

**Comment by gizmocuz** [comment]
Okey, call me a NOOB, but I still have no idea why this could be a Domoticz issue....

- SQLite used 'inside' Domoticz is statically linked, and only used inside Domoticz.
There is no way a external program/script is using this SQLite

- As far as my limited understanding regarding Python scripts, you need to declare the libraries/modules you want to use at the top of the script.
These modules have to be available to the system and can be installed by using the 'pip3' command line utility
This will install a SQLite python library ? Is this library stand-alone, and only used by Python, or is this a 'wrapper' against the existing sqlite library installed on the host system (Do note that Domoticz does NOT install this library)

**Comment by pipiche38** [comment]
@gizmocuz I'm sure that you have much more experience than I. My understanding is that Domoticz has also the Python Framework embedded. and from that SQL calls can be done, via a shared library load . As the shared library and the SQLite 'inside' has the same symbols then it makes some stuff strange when both are not the same SQLlite version.
This is at least my understanding.

I think someone from the BSD side, confirm it and said that Domoticz in BSD doesn't use the SQLite 'inside' but the shared lib. ( https://github.com/domoticz/domoticz/issues/4312#issuecomment-705539972 )

**Comment by gizmocuz** [comment]
It's a option to use SQLite as external library. This is a CMake option, but by default this is disabled.

We do not have the python framework embedded, we try to find the python library on the system and are in fact dynamically loading this

I am not aware of special 'Domoticz module' commands to directly manipulate or execute SQLite commands.
As far as I know (and related to this script) , SQLite is loaded as a python module ?

appdb.py
import sqlite3

(and asiosqlite)

So this is using a python module 'sqlite3'

Now assume that this 'sqlite3 module' is somewhere installed on your host system. It's probably  a binary library (compiled)
This library downloaded from somewhere, does have no idea about other processes on the system
So I still don't think that it is Domoticz related as it runs stand-alone

Anyway, you can very easily test this, just compile Domoticz yourself, and at the build step use

cmake -DCMAKE_BUILD_TYPE=Release -DUSE_BUILTIN_SQLITE=NO CMakeLists.txt

Now you should be able to test if this works correctly

**Comment by pipiche38** [comment]
yes, SQLite us loaded by a python module. Basically the setup is :

Domoticz ---> Python Framework --> Plugin  --> import sqlite3  
                                                                           --> call SQLite function

When importing the 'sqlite3' this indeed will load the SQLite shared library.

I do confirm from my previous test that "cmake -DCMAKE_BUILD_TYPE=Release -DUSE_BUILTIN_SQLITE=NO CMakeLists.txt" makes it working without issues

On the other side I do understand that for some cases it is easier for you to build with the SQLite 'inside' as this ease the deployment and installation.

**Comment by gizmocuz** [comment]
Yes it makes lives easier for people compiling as well.

Anyway I assume many more applications seem to do so and there should be no reason not doing so

Anyway, I previous demonstrated that SQLite (as python module) can be used without issues with a example script.
There seem to be a specific call method (PARSE_DECLTYPES ... whatever this is) that is failing.
Maybe you should have a small discussion with the people from SQLite as there should be no reason why applications are not being allowed to statically link this library

**Comment by pipiche38** [comment]
as stated, we have one binary ( Domoticz ) which is statically linked with 1 version of SQLIte (via the bultin version), and there the shared library of SQLite which then will be loaded when a python plugin import the sqlite3 module.
When both have the same version  of SQLite there is no issue at all, when there are on different level of sqlite3 there is a risk of issue.

The example you have provided indeed works. but you cannot conclude that a simple piece of code demonstrate that it works.

**Comment by gizmocuz** [comment]
Try at least to get the opinion from SQLite before thinking that this is the cause!
Every application should/is allowed to static link a library and that should have no influence on third party libraries
So please find the way to the SQLite issue location

**Comment by gizmocuz** [comment]
@puddly , Unfortunately I don't experiencing a crash with your example above.
But I have to say, when debugging, I use Windows, Visual Studio 2019 and Python 3.6 as 3.7 was giving me issues

I'm going to perform some tests.... It seems libsqlite3-0 is installed by default on Debian/Ubuntu and I suspect also on other systems as well. (Even my NAS has this library)

That means we maybe could link dynamically against this library by default .... 

First compile/test is working... I will adjust the CMake project and build instructions, build new Arm x86/x64 and Intel x64 beta's and make a new docker image and report back shortly ....

**Comment by gizmocuz** [comment]
It all still seems to run fine! Installed this on a Arm x86 and x64 and a system running Domoticz as a docker...
Hope this solves the python SQLite issues

**Comment by Hedda** [comment]
> It all still seems to run fine! Installed this on a Arm x86 and x64 and a system running Domoticz as a docker...
> Hope this solves the python SQLite issues

Good to hear Domoticz runs fine with SQLite library dynamically linked instead of statically linked. Upstream changes for reference:

https://github.com/domoticz/domoticz/commit/b34627e48eb2fcf96b5ce713741a638740d5d4eb

https://github.com/domoticz/domoticz/commit/0a4ccfb82a7b2f291c821a9ac71b3d8504e125b7

**Comment by puddly** [comment]
Excellent! The full Python 3.7.3 sqlite test suite now passes and the new Docker image has not crashed for me after over 20 restarts.

**Comment by pipiche38** [comment]
Thanks for @gizmocuz support
